ALTER TABLE rentals
  ADD COLUMN operator_name VARCHAR(255) NULL AFTER notes,
  ADD COLUMN delivery_method ENUM('CUSTOMER_PICKUP','COMPANY_DELIVERY') NOT NULL DEFAULT 'CUSTOMER_PICKUP' AFTER operator_name;
